######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 28 20:47:32 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += dbus

# Input
HEADERS += halobject.h test.h
SOURCES += halobject.cpp main.cpp test.cpp
